# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  # theme_day: minimal
  # theme_night: minimal
  theme_day: fliptheme
  font: flipfont
  # font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  block: flipfoot
  copyright:
    notice: '© {year} Flip Tanedo. This work is licensed under {license}. [Source on GitHub](https://github.com/fliptanedo/FlipWebsite2022). Published using [wowchemy](https://github.com/wowchemy/) for [Hugo](https://gohugo.io). Thanks to George Cushen.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    # theme_dark: dracula
    theme_dark: github-light
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/fliptanedo/FlipWebsite2023'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: mapnik
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true



## ADDED BY FLIP

email1: flip.tanedo # using cryptedmail
email2: ucr # using cryptedmail
email3: edu # using cryptedmail

# Feynman Diagram Footer
footmark: 'layout/feynmanfooter.png'

# Footer logos
midlogo: 'logo/UCRPAlogo2.png'
mylogo: 'logo/FlipAmbigram.png'

# watermark on the about widget
watermark: 'background/Bundle3.jpg'
## /FLIP

i_am_a_sponsor: true